#!/bin/bash
#


if dpkg-query -W -f='${Status}' apache2 | grep -c 'ok installed'
then
	if dpkg-query -W -f='${Status}' mysql-server | grep -c 'ok installed'
	then
        	clear
        	echo "Apache2 ja mysql on installitud"
        	service apache2 status
		service mysql status
	else
	sudo apt install -y apache2
	sudo apt install -y mysql-server
	fi
fi
