#!/bin/bash
#


if dpkg-query -W -f='${Status}' apache2 | grep -c 'ok installed'
then
	if dpkg-query -W -f='${Status}' php | grep -c 'ok installed'
	then
        	clear
        	echo "Apache2 ja Php on installitud"
        	service apache2 status
	else
	sudo apt install -y apache2
	sudo apt install -y php
	fi
fi
