#!/bin/bash
#

for user in $(cat /etc/passwd |cut -d ":" -f1)
do
	if ls /home/$user | grep "public_html"
	then
		echo "kasutajal $user on public kataloog olemas"
	else
		mkdir /home/$user/public_html
		echo "Tere $user!" > /home/$user/public_html/index.html
		chown -R 755 /home/$user/public_html
		chown -R $user:www-data /home/$user/public_html
		echo "Kasutjale $user tehti public kaust"
	fi
done
a2enmod userdir
service apache2 resart
