#!/bin/bash
#
for rida in $(cat kasutajad)
do
	kasutajanimi=$(echo $rida | awk -F":"'{print $1})
	parool=$(echo $rida | awk -F":"'{print $2})
	useradd -m -s /bin/bash $kasutajanimi
echo "$kasutajanimi:$parool" | chpasswd
done
